
export const localimag={
    email:require('../Icons/email.png'),
    password:require('../Icons/password.png'),
    splash:require('../Icons/new_logo.png'),
    back:require('../Icons/back.png'),
    user:require('../Icons/user.png'),
    notification:require('../Icons/notification.png'),
    resetpassword:require('../Icons/resetpassword.png'),
    terms:require('../Icons/terms.png'),
    privacy:require('../Icons/privacy.png'),
    about:require('../Icons/about.png'),
    contact:require('../Icons/contact.png'),
    rate:require('../Icons/rate.png'),
    shareapp:require('../Icons/shareapp.png'),
    logout:require('../Icons/logout.png'),
    userplaceholder:require('../Icons/userplaceholder.png'),
    dots:require('../Icons/dots.png'),
    camera:require('../Icons/camera.png'),
    share:require('../Icons/share.png'),
    pen:require('../Icons/pen.png'),
    no_data:require('../Icons/no_data.png'),
    cancel:require('../Icons/cancel.png'),
    down:require('../Icons/down.png'),
    up_arrow:require('../Icons/up_arrow.png'),
    userplaceholder:require('../Icons/userplaceholder.png'),
       //use for this aap
    user_icon:require('../Icons/user-icon.png'),
    call_icon:require('../Icons/call-icon.png'),
    email_icon:require('../Icons/email-icon.png'),
    location_black:require('../Icons/location_black.png'),
    location_icon:require('../Icons/location-=icon.png'),
    logo_1024:require('../Icons/logo-1024.png'),
    logo_512:require('../Icons/logo-512.png'),
    Group1313:require('../Icons/Group1313.png'),
    Group1312:require('../Icons/Group1312.png'),
    pass_icon:require('../Icons/pass-icon.png'),
    activate_hm_icon:require('../Icons/activate-hm-icon.png'),
    home_active:require('../Icons/home_active.png'),
    chat_active:require('../Icons/chat_active.png'),
    handmade:require('../Icons/handmade.png'),
    handmade_Active:require('../Icons/handmade_Active.png'),
    workhand_active:require('../Icons/workhand_active.png'),
    workhand:require('../Icons/workhand.png'),
    profile_deactive:require('../Icons/profile_deactive.png'),
    profile_active:require('../Icons/profile_active.png'),
    img_02:require('../Icons/img-02.png'),
    Frame5:require('../Icons/Frame5.png'),
    posts:require('../Icons/posts.png'),
    job_post_0c3:require('../Icons/job-post-0c3.png'),
    post_03:require('../Icons/post-03.png'),    
    people_white:require('../Icons/people_white.png'),
    profile_icon:require('../Icons/profile-icon.png'),
    restaurant_name:require('../Icons/restaurant_name.png'),
    notif_1:require('../Icons/notif-1.png'),
    notif_02:require('../Icons/notif-02.png'),
    Group1298:require('../Icons/Group1298.png'),
    notifications_witout_dot:require('../Icons/notifications_witout_dot.png'),
    search_01:require('../Icons/search-01.png'),
    img_01:require('../Icons/img-01.png'),
    img_02_1:require('../Icons/img-02-1.png'),
    img_03:require('../Icons/img-03.png'),
    check_icon_c2:require('../Icons/check-icon-c2.png'),
    logo_1:require('../Icons/logo-1.png'),
    Group_1246:require('../Icons/Group_1246.png'),
    profile_1:require('../Icons/profile-1.png'),
    profile_02:require('../Icons/profile-02.png'),
    profile_03:require('../Icons/profile-03.png'),
    terms_and_conditions:require('../Icons/terms-and-conditions.png'),
    star:require('../Icons/star.png'),
    sharing:require('../Icons/sharing.png'),
    phone_call:require('../Icons/phone-call.png'),
    padlock:require('../Icons/padlock.png'),
    help:require('../Icons/help.png'),
    insurance:require('../Icons/insurance.png'),
    delete:require('../Icons/delete.png'),
    info:require('../Icons/info.png'),
    pen131:require('../Icons/pen131.png'),
    file2:require('../Icons/file2.png'),
    steve_johnson_0SLVz06gniE_unsplash:require('../Icons/steve-johnson-0SLVz06gniE-unsplash.jpg'),
    Mask_group:require('../Icons/Mask_group.png'),
    clock2:require('../Icons/clock2.png'),
    cesar_couto_OB2F6CsMva8_unsplash1:require('../Icons/cesar-couto-OB2F6CsMva8-unsplash1.jpg'),
    cesar_couto_OB2F6CsMva8_unsplash:require('../Icons/cesar-couto-OB2F6CsMva8-unsplash.jpg'),
    checked:require('../Icons/checked.png'),
    check:require('../Icons/check.png'),
    down4:require('../Icons/down4.png'),
    Group1330:require('../Icons/Group1330.png'),
    menu:require('../Icons/menu.png'),
    new_window2:require('../Icons/new-window2.png'),
    pen6:require('../Icons/pen6.png'),
    button3:require('../Icons/button3.png'),
    Group1266:require('../Icons/Group1266.png'),
    Group1315:require('../Icons/Group1315.png'),
    Rectangle360:require('../Icons/Rectangle360.png'),
    check1:require('../Icons/check1.png'),
    Group1269:require('../Icons/Group1269.png'),
    Group1268:require('../Icons/Group1268.png'),
    chat2:require('../Icons/chat2.png'),
    checked2 :require('../Icons/checked2.png'),
    saved_icon :require('../Icons/saved-icon.png'),
    mine_icon :require('../Icons/mine-icon.png'),
    bookmark3 :require('../Icons/bookmark3.png'),
    bookmark14 :require('../Icons/bookmark14.png'),
    down251 :require('../Icons/down251.png'),
    Ellipse31 :require('../Icons/Ellipse31.png'),
    Group1298 :require('../Icons/Group1298.png'),
    job2 :require('../Icons/job2.png'),
    job_1_21 :require('../Icons/job-1-21.png'),
    suitcase2 :require('../Icons/suitcase2.png'),
    suitcase3 :require('../Icons/suitcase3.png'),
    user3 :require('../Icons/user3.png'),
    user12 :require('../Icons/user12.png'),
    gallery2_1 :require('../Icons/gallery2-1.png'),
    gallery2 :require('../Icons/gallery2.png'),
    home23 :require('../Icons/home23.png'),
    home2 :require('../Icons/home2.png'),
    button4 :require('../Icons/button4.png'),
    magnifying_glass2 :require('../Icons/magnifying-glass2.png'),
    share5 :require('../Icons/share5.png'),
    like5 :require('../Icons/like5.png'),
    camera1 :require('../Icons/camera1.png'),
    oval_black_speech_bubble5 :require('../Icons/oval-black-speech-bubble5.png'),
    Group1311 :require('../Icons/Group1311.png'),
    Ellipse68 :require('../Icons/Ellipse68.png'),
    Group1310 :require('../Icons/Group1310.png'),
    Group1325 :require('../Icons/Group1325.png'),
    image :require('../Icons/image.png'),
    plus :require('../Icons/plus.png'),
    plus_small22 :require('../Icons/plus-small22.png'),
    settings2 :require('../Icons/settings2.png'),
    comment3 :require('../Icons/comment3.png'),
    Group1253 :require('../Icons/Group1253.png'),
    history12 :require('../Icons/history12.png'),
    add12 :require('../Icons/add12.png'),
    setting12 :require('../Icons/setting12.png'),
    bullet_icon_c1 :require('../Icons/bullet-icon-c1.png'),
    back :require('../Icons/back.png'),
    back2 :require('../Icons/back2.png'),
    back_arrow_icon_c1 :require('../Icons/back-arrow-icon-c1.png'),
    attach_paperclip_symbol2:require('../Icons/attach-paperclip-symbol2.png'),
    photo_camera_interface_symbol_for_button2:require('../Icons/photo-camera-interface-symbol-for-button2.png'),
    karla_caloca_JlL1GumRqJ4_unsplash:require('../Icons/karla-caloca-JlL1GumRqJ4-unsplash.jpg'),
    toa_heftiba_FV3GConVSss_unsplash:require('../Icons/toa-heftiba-FV3GConVSss-unsplash.jpg'),
    aaina_sharma_J8iOJZEPFQ4_unsplash:require('../Icons/aaina-sharma-J8iOJZEPFQ4-unsplash.jpg'),
    designecologist_Pmh0UoG1vlE_unsplash:require('../Icons/designecologist-Pmh0UoG1vlE-unsplash.jpg'),

 

    
}